// <auto-generated>
// This file was generated by scripts/generate_native_library.py
// Source: z3_api.h / Parser interface
// DO NOT EDIT - Changes will be overwritten
// </auto-generated>

using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;

namespace Spaceorc.Z3Wrap.Core.Interop2;

internal sealed partial class NativeLibrary2
{
    private static void LoadFunctionsParserInterface(IntPtr handle, Dictionary<string, IntPtr> functionPointers)
    {
        LoadFunctionOrNull(handle, functionPointers, "Z3_parse_smtlib2_string");
        LoadFunctionOrNull(handle, functionPointers, "Z3_parse_smtlib2_file");
        LoadFunctionOrNull(handle, functionPointers, "Z3_eval_smtlib2_string");
        LoadFunctionOrNull(handle, functionPointers, "Z3_mk_parser_context");
        LoadFunctionOrNull(handle, functionPointers, "Z3_parser_context_inc_ref");
        LoadFunctionOrNull(handle, functionPointers, "Z3_parser_context_dec_ref");
        LoadFunctionOrNull(handle, functionPointers, "Z3_parser_context_add_sort");
        LoadFunctionOrNull(handle, functionPointers, "Z3_parser_context_add_decl");
        LoadFunctionOrNull(handle, functionPointers, "Z3_parser_context_from_string");
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate IntPtr parse_smtlib2_stringDelegate(IntPtr c, IntPtr str, uint num_sorts, IntPtr sort_names, IntPtr sorts, uint num_decls, IntPtr decl_names, IntPtr decls);

    internal IntPtr Z3_parse_smtlib2_string(IntPtr c, IntPtr str, uint num_sorts, IntPtr sort_names, IntPtr sorts, uint num_decls, IntPtr decl_names, IntPtr decls)
    {
        var funcPtr = GetFunctionPointer("Z3_parse_smtlib2_string");
        var func = Marshal.GetDelegateForFunctionPointer<parse_smtlib2_stringDelegate>(funcPtr);
        return func(c, str, num_sorts, sort_names, sorts, num_decls, decl_names, decls);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate IntPtr parse_smtlib2_fileDelegate(IntPtr c, IntPtr file_name, uint num_sorts, IntPtr sort_names, IntPtr sorts, uint num_decls, IntPtr decl_names, IntPtr decls);

    internal IntPtr Z3_parse_smtlib2_file(IntPtr c, IntPtr file_name, uint num_sorts, IntPtr sort_names, IntPtr sorts, uint num_decls, IntPtr decl_names, IntPtr decls)
    {
        var funcPtr = GetFunctionPointer("Z3_parse_smtlib2_file");
        var func = Marshal.GetDelegateForFunctionPointer<parse_smtlib2_fileDelegate>(funcPtr);
        return func(c, file_name, num_sorts, sort_names, sorts, num_decls, decl_names, decls);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate IntPtr eval_smtlib2_stringDelegate(IntPtr c, IntPtr str);

    internal IntPtr Z3_eval_smtlib2_string(IntPtr c, IntPtr str)
    {
        var funcPtr = GetFunctionPointer("Z3_eval_smtlib2_string");
        var func = Marshal.GetDelegateForFunctionPointer<eval_smtlib2_stringDelegate>(funcPtr);
        return func(c, str);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate IntPtr mk_parser_contextDelegate(IntPtr c);

    internal IntPtr Z3_mk_parser_context(IntPtr c)
    {
        var funcPtr = GetFunctionPointer("Z3_mk_parser_context");
        var func = Marshal.GetDelegateForFunctionPointer<mk_parser_contextDelegate>(funcPtr);
        return func(c);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void parser_context_inc_refDelegate(IntPtr c, IntPtr pc);

    internal void Z3_parser_context_inc_ref(IntPtr c, IntPtr pc)
    {
        var funcPtr = GetFunctionPointer("Z3_parser_context_inc_ref");
        var func = Marshal.GetDelegateForFunctionPointer<parser_context_inc_refDelegate>(funcPtr);
        func(c, pc);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void parser_context_dec_refDelegate(IntPtr c, IntPtr pc);

    internal void Z3_parser_context_dec_ref(IntPtr c, IntPtr pc)
    {
        var funcPtr = GetFunctionPointer("Z3_parser_context_dec_ref");
        var func = Marshal.GetDelegateForFunctionPointer<parser_context_dec_refDelegate>(funcPtr);
        func(c, pc);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void parser_context_add_sortDelegate(IntPtr c, IntPtr pc, IntPtr s);

    internal void Z3_parser_context_add_sort(IntPtr c, IntPtr pc, IntPtr s)
    {
        var funcPtr = GetFunctionPointer("Z3_parser_context_add_sort");
        var func = Marshal.GetDelegateForFunctionPointer<parser_context_add_sortDelegate>(funcPtr);
        func(c, pc, s);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate void parser_context_add_declDelegate(IntPtr c, IntPtr pc, IntPtr f);

    internal void Z3_parser_context_add_decl(IntPtr c, IntPtr pc, IntPtr f)
    {
        var funcPtr = GetFunctionPointer("Z3_parser_context_add_decl");
        var func = Marshal.GetDelegateForFunctionPointer<parser_context_add_declDelegate>(funcPtr);
        func(c, pc, f);
    }

    [UnmanagedFunctionPointer(CallingConvention.Cdecl)]
    private delegate IntPtr parser_context_from_stringDelegate(IntPtr c, IntPtr pc, IntPtr s);

    internal IntPtr Z3_parser_context_from_string(IntPtr c, IntPtr pc, IntPtr s)
    {
        var funcPtr = GetFunctionPointer("Z3_parser_context_from_string");
        var func = Marshal.GetDelegateForFunctionPointer<parser_context_from_stringDelegate>(funcPtr);
        return func(c, pc, s);
    }

}
