name: Release

on:
  workflow_dispatch:   # manual trigger from GitHub Actions UI

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Install Z3
        run: |
          sudo apt-get update
          sudo apt-get install -y libz3-4
      - run: dotnet restore
      - run: dotnet build -c Release --no-restore
      - run: dotnet test -c Release --no-build

      - name: Extract notes from CHANGELOG [Unreleased]
        shell: bash
        run: |
          awk '
            BEGIN { in=0 }
            /^## \[Unreleased\]/ { in=1; next }
            /^## \[/ { if (in) exit }
            in { print }
          ' CHANGELOG.md > RELEASE_NOTES.md
          if [ ! -s RELEASE_NOTES.md ]; then echo "No notes under [Unreleased]." > RELEASE_NOTES.md; fi

      - name: Pack (inject release notes)
        run: |
          NOTES="$(sed ':a;N;$!ba;s/\r//g' RELEASE_NOTES.md)"  # normalize newlines
          dotnet pack -c Release --no-build -o artifacts \
            -p:PackageReleaseNotes="$NOTES"

      - run: dotnet pack -c Release --no-build -o artifacts

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: artifacts/*.nupkg