name: release

on:
  workflow_dispatch:   # manual trigger from GitHub Actions UI

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: Install Z3
        run: |
          sudo apt-get update
          sudo apt-get install -y libz3-4
      - run: dotnet restore
      - run: dotnet build -c Release --no-restore
      - run: dotnet test -c Release --no-build
      - run: dotnet pack -c Release --no-build -o artifacts

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: artifacts/*.nupkg