name: release

on:
  workflow_dispatch:

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install Z3
        run: |
          sudo apt-get update
          sudo apt-get install -y libz3-4

      - run: dotnet restore
      - run: dotnet build -c Release --no-restore
      - run: dotnet test -c Release --no-build

      - name: Extract notes from CHANGELOG [Unreleased]
        run: scripts/extract-notes.sh --section "Unreleased" --output "RELEASE_NOTES.md"

      - name: Pack (inject release notes)
        run: |
          NOTES="$(sed ':a;N;$!ba;s/\r//g' RELEASE_NOTES.md)"
          dotnet pack -c Release --no-build -o artifacts \
            -p:PackageReleaseNotes="$NOTES"

      - name: Add version to job summary
        run: |
          VER=$(dotnet msbuild Z3Wrap/Z3Wrap.csproj -t:PrintMinVer -v:m \
            | sed -n 's/.*MinVer_PackageVersion=\(.*\)$/\1/p' | tail -n1)
          echo "### Package version" >> $GITHUB_STEP_SUMMARY
          echo "\`$VER\`" >> $GITHUB_STEP_SUMMARY


      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: |
            artifacts/*.nupkg
            artifacts/*.snupkg
