name: release-notes

on:
  push:
    tags:
      - 'v*'                   # still works for tags you push locally
  workflow_run:
    workflows: ["tag"]         # <- runs after your tag workflow finishes
    types: [completed]
  workflow_dispatch: {}        # manual fallback

permissions:
  contents: write

jobs:
  draft_release_with_notes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      # Determine which tag to use
      - name: Determine tag
        id: tag
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "push" ]; then
            echo "name=${GITHUB_REF_NAME}" >> $GITHUB_OUTPUT
          else
            echo "name=$(git describe --tags --abbrev=0)" >> $GITHUB_OUTPUT
          fi

      - name: Extract notes from CHANGELOG [Unreleased]
        run: scripts/extract-notes.sh --section "Unreleased" --output "RELEASE_NOTES.md"

      - name: Detect prerelease
        id: flags
        run: |
          TAG='${{ steps.tag.outputs.name }}'
          if [[ "$TAG" == *-* ]]; then echo "pre=true" >> $GITHUB_OUTPUT; else echo "pre=false" >> $GITHUB_OUTPUT; fi

      - name: Create GitHub Release (draft)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.tag.outputs.name }}
          draft: true
          prerelease: ${{ steps.flags.outputs.pre }}
          body_path: RELEASE_NOTES.md
