name: Release

on:
  workflow_dispatch:

jobs:
  pack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Install Z3
        run: |
          sudo apt-get update
          sudo apt-get install -y libz3-4

      - run: dotnet restore
      - run: dotnet build -c Release --no-restore
      - run: dotnet test -c Release --no-build

      - name: Extract notes from CHANGELOG [Unreleased]
        run: |
          python3 - <<'PY'
          import re, pathlib
          text = pathlib.Path("CHANGELOG.md").read_text(encoding="utf-8")
          m = re.search(r'^## \[Unreleased\]\s*(.*?)^## \[', text, flags=re.M|re.S) \
              or re.search(r'^## \[Unreleased\]\s*(.*)\Z', text, flags=re.M|re.S)
          notes = (m.group(1).strip() if m else '')
          pathlib.Path("RELEASE_NOTES.md").write_text(notes or "No notes under [Unreleased].", encoding="utf-8")
          PY

      - name: Pack (inject release notes)
        run: |
          NOTES="$(sed ':a;N;$!ba;s/\r//g' RELEASE_NOTES.md)"
          dotnet pack -c Release --no-build -o artifacts \
            -p:PackageReleaseNotes="$NOTES"

      - name: Show resolved version (MinVer)
        run: dotnet msbuild Z3Wrap/Z3Wrap.csproj -t:PrintMinVer -v:d || true

      - name: Upload packages
        uses: actions/upload-artifact@v4
        with:
          name: nuget-packages
          path: |
            artifacts/*.nupkg
            artifacts/*.snupkg
