name: tag

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Explicit version (X.Y.Z) - overrides bump"
        type: string
        required: false
      bump:
        description: "Version bump type"
        type: choice
        options: [patch, minor, major]
        default: patch
      prerelease:
        description: "Create prerelease tag?"
        type: boolean
        default: true
      prerelease_label:
        description: "Prerelease label (e.g., beta, rc, alpha)"
        type: string
        default: beta
      dry_run:
        description: "Dry run (show what would happen)"
        type: boolean
        default: false

permissions:
  contents: write

jobs:
  create_tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
      dry_run: ${{ inputs.dry_run }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Need full history for version calculations

      - name: Make tag script executable
        run: chmod +x scripts/tag.sh

      - name: Configure Git identity
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Create tag using tag.sh script
        id: tag
        env:
          INPUT_VERSION: ${{ inputs.version }}
          INPUT_BUMP: ${{ inputs.bump }}
          INPUT_PRERELEASE: ${{ inputs.prerelease }}
          INPUT_PRERELEASE_LABEL: ${{ inputs.prerelease_label }}
          INPUT_PREFIX: v
          INPUT_DRY_RUN: ${{ inputs.dry_run }}
        run: |
          # Execute tag script in GitHub Actions mode
          new_tag=$(scripts/tag.sh --github-actions)

          # Capture the tag name for downstream jobs
          echo "tag=${new_tag}" >> "$GITHUB_OUTPUT"